// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwBrOOZ7dE6Qf8DrP8uBZ2wCs2bzwaQ2Q',
    appId: '1:719127695243:web:af9b4603e326bab873e98e',
    messagingSenderId: '719127695243',
    projectId: 'meal-sharing-a45d6',
    authDomain: 'meal-sharing-a45d6.firebaseapp.com',
    storageBucket: 'meal-sharing-a45d6.firebasestorage.app',
    measurementId: 'G-ZBXWRHFLBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzVoJfS4BawkKpBmdYEhYRLZMD45Z9Wh4',
    appId: '1:719127695243:android:9698afee4301160a73e98e',
    messagingSenderId: '719127695243',
    projectId: 'meal-sharing-a45d6',
    storageBucket: 'meal-sharing-a45d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ipd3hUnFx8HJJjJANaA4PQgfdRWBQss',
    appId: '1:719127695243:ios:4289ad733a4ba40673e98e',
    messagingSenderId: '719127695243',
    projectId: 'meal-sharing-a45d6',
    storageBucket: 'meal-sharing-a45d6.firebasestorage.app',
    androidClientId: '719127695243-4j9g3g1g7p15qoo70j9c2q1m5vcpm02a.apps.googleusercontent.com',
    iosClientId: '719127695243-2tjhare01gr6d4a9e4jo2gqb2470jfa4.apps.googleusercontent.com',
    iosBundleId: 'com.mealsharing.mealSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ipd3hUnFx8HJJjJANaA4PQgfdRWBQss',
    appId: '1:719127695243:ios:4289ad733a4ba40673e98e',
    messagingSenderId: '719127695243',
    projectId: 'meal-sharing-a45d6',
    storageBucket: 'meal-sharing-a45d6.firebasestorage.app',
    androidClientId: '719127695243-4j9g3g1g7p15qoo70j9c2q1m5vcpm02a.apps.googleusercontent.com',
    iosClientId: '719127695243-2tjhare01gr6d4a9e4jo2gqb2470jfa4.apps.googleusercontent.com',
    iosBundleId: 'com.mealsharing.mealSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwBrOOZ7dE6Qf8DrP8uBZ2wCs2bzwaQ2Q',
    appId: '1:719127695243:web:c54f0d4580e05b3d73e98e',
    messagingSenderId: '719127695243',
    projectId: 'meal-sharing-a45d6',
    authDomain: 'meal-sharing-a45d6.firebaseapp.com',
    storageBucket: 'meal-sharing-a45d6.firebasestorage.app',
    measurementId: 'G-238CBQ1PCQ',
  );

}